mappings:
  MockDataGenerator: SilverStripe\MockDataObjects\MockDataGenerator
  MockDataLog: SilverStripe\MockDataObjects\MockDataLog
  MockChildrenController: SilverStripe\MockDataObjects\MockChildrenController
  MockTimeField: SilverStripe\MockDataObjects\MockTimeField
  MockDecimalField: SilverStripe\MockDataObjects\MockDecimalField
  MockDoubleField: SilverStripe\MockDataObjects\MockDoubleField
  MockIntField: SilverStripe\MockDataObjects\MockIntField
  MockDateField: SilverStripe\MockDataObjects\MockDateField
  MockDBField: SilverStripe\MockDataObjects\MockDBField
  MockDatetimeField: SilverStripe\MockDataObjects\MockDatetimeField
  MockFloatField: SilverStripe\MockDataObjects\MockFloatField
  MockBooleanField: SilverStripe\MockDataObjects\MockBooleanField
  MockTextField: SilverStripe\MockDataObjects\MockTextField
  MockHTMLVarcharField: SilverStripe\MockDataObjects\MockHTMLVarcharField
  MockYearField: SilverStripe\MockDataObjects\MockYearField
  MockHTMLTextField: SilverStripe\MockDataObjects\MockHTMLTextField
  MockPercentageField: SilverStripe\MockDataObjects\MockPercentageField
  MockCurrencyField: SilverStripe\MockDataObjects\MockCurrencyField
  MockVarcharField: SilverStripe\MockDataObjects\MockVarcharField
  MockDataObjectGridFieldConfig: SilverStripe\MockDataObjects\MockDataObjectGridFieldConfig
  MockDataObject: SilverStripe\MockDataObjects\MockDataObject
  MockViewableData: SilverStripe\MockDataObjects\MockViewableData
  MockDataCMS: SilverStripe\MockDataObjects\MockDataCMS
  MockDataSiteTree: SilverStripe\MockDataObjects\MockDataSiteTree
  MockDataGridFieldItemRequest: SilverStripe\MockDataObjects\MockDataGridFieldItemRequest
  MockDataBuilder: SilverStripe\MockDataObjects\MockDataBuilder
  MockDataTask: SilverStripe\MockDataObjects\MockDataTask
